require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Lint/Debugger:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageChain:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Naming/MethodName:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Spec/InstanceVariable:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
  
Style/SymbolProc:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/For:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/NegatedIf:
  Enabled: false