version: 2.1
executors:
  default:
    working_directory: ~/TheInternetRspec
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.3-node-browsers

caches: 
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}

commands:
  bundle:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run:
          name: Install gems 
          command: |
            gem update --system
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --retry 3
            bundle update
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle

  rspec:
    steps:
      - run: bundle exec rspec

jobs:
  bundle:
    executor: default
    steps:
      - bundle
  lintering:
    executor: default
    steps:
      - bundle
  rspec:
    parallelism: 4
    executor: default
    steps:
      - bundle
      - rspec

workflows:
  version: 2.1
  build:
    jobs:
      - bundle
      - rspec

