version: 2.1

executors:
  default:
    working_directory: ~/TheInternetRspec
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

caches:
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}

commands:
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop

  run_specs:
    steps:
      - run:
          name: run specs
          command: rspec
jobs:
  lintering:
    executor: default
    steps:
      - run_linters
  run_specs:
    executor: default
    steps:
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering