version: 2.1

executors:
  default:
    working_directory: ~/TheInternetRspec
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

caches:
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}

commands:
  setup_all:
    steps:
    - run: gem install bundler -v 2.3.11
    - run: bundle install
    - run: rails generate rspec:install
    
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: gem update --system
      - run: bundle update --bundler
jobs:
  run_specs:
    executor: default
    steps:
      - setup_all
      - setup_environment
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - run_specs